export const NIGERIAN_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT - Abuja",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
]

export const FOOD_CATEGORIES = [
  "Rice Dishes",
  "Soups & Stews",
  "Grilled & Fried",
  "Snacks & Appetizers",
  "Swallow Foods",
  "Beverages",
  "Spices & Seasonings",
  "Dried Foods",
  "Fresh Produce",
  "Packaged Foods",
]

export const FOOD_SUBCATEGORIES = {
  "Rice Dishes": ["Jollof Rice", "Fried Rice", "Coconut Rice", "Ofada Rice", "Tuwo Shinkafa"],
  "Soups & Stews": ["Egusi", "Okra Soup", "Pepper Soup", "Banga Soup", "Oha Soup", "Afang Soup"],
  "Grilled & Fried": ["Suya", "Peppered Chicken", "Fish Pepper Soup", "Grilled Tilapia", "Fried Plantain"],
  "Snacks & Appetizers": ["Puff Puff", "Meat Pie", "Chin Chin", "Akara", "Moi Moi"],
  "Swallow Foods": ["Pounded Yam", "Eba", "Amala", "Fufu", "Semo"],
  Beverages: ["Palm Wine", "Zobo", "Kunu", "Chapman", "Tiger Nut Drink"],
  "Spices & Seasonings": ["Curry Powder", "Thyme", "Bay Leaves", "Locust Beans", "Cameroon Pepper"],
  "Dried Foods": ["Stockfish", "Dried Fish", "Crayfish", "Dried Pepper", "Ogbono"],
  "Fresh Produce": ["Plantain", "Yam", "Cassava", "Sweet Potato", "Vegetables"],
  "Packaged Foods": ["Garri", "Semolina", "Rice", "Beans", "Palm Oil"],
}
